package Paq_Interfaz;

import java.awt.Image;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ACMK
 */
public class Frm_Menu extends javax.swing.JFrame implements Runnable {

    private String ampm;
    private String hora;
    private String minutos;
    private String segundos;
    private ImageIcon icon1 = new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.png"));
    private Thread h1;
    private int i = 0;
    public String usuario;
    java.sql.Connection conn;
    Paq_Base_Datos.Operaciones_BD operaciones = new Paq_Base_Datos.Operaciones_BD();
    Paq_Clases.Cla_Ruta ruta = new Paq_Clases.Cla_Ruta();
    private Object fecha;

    /**
     * Creates new form menu
     */
    public Frm_Menu() {
        //Constructor por defecto carga look inicia componentes ejecuta el hilo
        this.look();
        initComponents();
        h1 = new Thread(this);
        h1.start();
        setLocationRelativeTo(null);
        setVisible(true);
        this.Llenar();
        this.Ajustar(lblFondo, icon1);
        lblfecha.setText(new Paq_Clases.Cla_Fecha().getFecha());
    }

    public void Llenar() {
        try {
            String sql = "select * from clientes";
            ResultSet rs = operaciones.Consultar(sql);
            while (rs.next()) {
                if (rs.getString("primer_nombre") == null) {
                    cbxN.addItem(rs.getString("nombre_empresa"));
                } else {
                    cbxN.addItem(rs.getString("primer_nombre") + " " + rs.getString("primer_apellido"));
                }
            }
            operaciones.conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void look() {
        //este metodo establece el look and feels de la aplicacion
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Ajustar(JLabel label, ImageIcon icon) {
        //esta funcion ajusta un icono(parametro) al tamaño del label (parametro)
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMonthChooser2 = new com.toedter.calendar.JMonthChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jFrame4 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        cbxN = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jFrame5 = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jFrame6 = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        cbxL = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblfecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(300, 150));
        jFrame1.setResizable(false);
        jFrame1.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jFrame1WindowLostFocus(evt);
            }
        });
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione la fecha a consultar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, -1));

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, -1));

        jFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 120));

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setMinimumSize(new java.awt.Dimension(300, 150));
        jFrame2.setResizable(false);
        jFrame2.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jFrame2WindowLostFocus(evt);
            }
        });
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seleccione el mes a consultar:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));

        jMonthChooser2.setDayChooser(null);
        jPanel3.add(jMonthChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 100, -1));

        jButton4.setText("Consultar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, -1));

        jFrame2.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 120));

        jFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame3.setMinimumSize(new java.awt.Dimension(300, 150));
        jFrame3.setResizable(false);
        jFrame3.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jFrame3WindowLostFocus(evt);
            }
        });
        jFrame3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel4.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seleccione el Año a consultar:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));

        jButton6.setText("Consultar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, -1));
        jPanel4.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 100, -1));

        jFrame3.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 120));

        jFrame4.setMinimumSize(new java.awt.Dimension(510, 160));
        jFrame4.setResizable(false);
        jFrame4.setSize(new java.awt.Dimension(510, 160));
        jFrame4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 51), new java.awt.Color(0, 153, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 153, 51)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 3, 14), new java.awt.Color(0, 153, 51))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel7.setText("Seleccione un cliente de la lista");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 220, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Cedula/RIF");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 30));

        txtC.setEditable(false);
        txtC.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtC.setEnabled(false);
        txtC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCMouseClicked(evt);
            }
        });
        jPanel5.add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 90, 30));

        cbxN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNActionPerformed(evt);
            }
        });
        jPanel5.add(cbxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 170, 30));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Consultar-10.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Consultar-14.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras-10.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras-14.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Nombre/Empresa");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jFrame4.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 160));

        jFrame5.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame5.setMinimumSize(new java.awt.Dimension(300, 150));
        jFrame5.setResizable(false);
        jFrame5.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jFrame5WindowLostFocus(evt);
            }
        });
        jFrame5.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel6.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel6.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Seleccione la fecha de ingreso:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));
        jPanel6.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, -1));

        jButton8.setText("Consultar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButton9.setText("Cancelar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, -1));

        jFrame5.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 120));

        jFrame6.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame6.setMinimumSize(new java.awt.Dimension(300, 150));
        jFrame6.setResizable(false);
        jFrame6.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jFrame6WindowLostFocus(evt);
            }
        });
        jFrame6.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel7.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel7.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Seleccione linea de producto:");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));

        jButton12.setText("Consultar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, -1));

        cbxL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laton", "Ferroso", "Bronce", "Hierro" }));
        jPanel7.add(cbxL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 30));

        jFrame6.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 120));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tornavica.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 310, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEMA DE VENTAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 440, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar sesion-10.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar sesion-14.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 112, 32));

        lblfecha.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        lblfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfecha.setText("fecha");
        jPanel2.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 130, 30));

        lblUsuario.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario:");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 90, 30));

        lblFondo.setMaximumSize(new java.awt.Dimension(700, 400));
        lblFondo.setMinimumSize(new java.awt.Dimension(700, 400));
        lblFondo.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel2.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 320));

        jMenuBar1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(100, 21));

        jMenu1.setText("Inventario");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jMenu1.setName(""); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498176758_human-folder-tar.png"))); // NOI18N
        jMenuItem1.setText("Consultar Inventario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498177689_gnome-mime-application-x-bzip-compressed-tar.png"))); // NOI18N
        jMenuItem2.setText("Añadir Nuevo Producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");
        jMenu2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498177652_document-open.png"))); // NOI18N
        jMenuItem4.setText("Consultar Ventas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addreport32x32.png"))); // NOI18N
        jMenuItem5.setText("Añadir Nueva Ventas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Clientes");
        jMenu3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultacliente32x32.png"))); // NOI18N
        jMenuItem7.setText("Consultar Clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem13.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir cliente32x32.png"))); // NOI18N
        jMenuItem13.setText("Añadir Nuevo Cliente");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Proveedores");
        jMenu4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498176612_human-folder-public.png"))); // NOI18N
        jMenuItem9.setText("Consultar Proveedor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem15.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498176515_contact-new.png"))); // NOI18N
        jMenuItem15.setText("Añadir Nuevo Proveedor");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Gestion");
        jMenu5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login 32x32.png"))); // NOI18N
        jMenuItem11.setText("Gestion Usuarios");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1494531821_application-vnd.ms-excel.png"))); // NOI18N
        jMenuItem3.setText("Gestion Reportes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem19.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498177689_gnome-mime-application-x-bzip-compressed-tar.png"))); // NOI18N
        jMenuItem19.setText("Gestion Inventario");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem19);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Reportes");
        jMenu7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1494531821_application-vnd.ms-excel.png"))); // NOI18N
        jMenu6.setText("Ventas");
        jMenu6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem6.setText("Listado Ventas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem12.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem12.setText("Consulta Ventas por Fecha");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem16.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem16.setText("Ventas por Clientes");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenu7.add(jMenu6);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498177689_gnome-mime-application-x-bzip-compressed-tar.png"))); // NOI18N
        jMenu8.setText("Inventario");
        jMenu8.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        jMenuItem17.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem17.setText("Listado Productos");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17);

        jMenuItem23.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem23.setText("Consulta por Fecha de ingreso ");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem24.setText("Consulta por Linea de Producto");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem24);

        jMenuItem25.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem25.setText("Prod. por debajo del minimo");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem25);

        jMenuItem26.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem26.setText("Prod. por encima del maximo");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem26);

        jMenuItem27.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem27.setText("Prod. por debajo del Inventario Seguridad");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem27);

        jMenu7.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498177675_stock_new-labels.png"))); // NOI18N
        jMenu9.setText("Clientes");
        jMenu9.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem8.setText("Listado Clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem21.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem21.setText("Listado Clientes Naturales");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem21);

        jMenuItem22.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem22.setText("Listado Clientes Juridicos");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem22);

        jMenu7.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498176758_human-folder-tar.png"))); // NOI18N
        jMenu10.setText("Proveedores");
        jMenu10.setToolTipText("");
        jMenu10.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem10.setText("Listado Proveedores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem10);

        jMenuItem18.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem18.setText("Listado Proveedores Activos");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem18);

        jMenuItem20.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem20.setText("Listado Proveedores Inactivos");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem20);

        jMenu7.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1498176612_human-folder-public.png"))); // NOI18N
        jMenu11.setText("Usuarios");
        jMenu11.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jMenuItem14.setText("Listado Usuarios");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem14);

        jMenu7.add(jMenu11);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usuario = "";
        lblUsuario.setText("Usuario: ");
        this.dispose();
        new Paq_Interfaz.Frm_login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new Paq_Interfaz.Frm_ClientesC().setVisible(true);

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        new Paq_Interfaz.Frm_ClientesA().setVisible(true);

    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        new Paq_Interfaz.Frm_ProveedoresA().setVisible(true);

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new Paq_Interfaz.Frm_ProveedoresC().setVisible(true);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Paq_Interfaz.Frm_InventarioC().setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int seleccion = JOptionPane.showOptionDialog(
                null,
                "¿Desea ingresar un producto nuevo o añadir a uno existente?",
                "Selector de opciones",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Nuevo", "Existente"}, // null para YES, NO y CANCEL
                "Nuevo");
        if (seleccion == 0) {
            Paq_Interfaz.Frm_InventarioA ventana = new Paq_Interfaz.Frm_InventarioA();
            ventana.setVisible(true);
            ventana.txtR.setText(usuario);
        } else if (seleccion == 1) {
            Paq_Interfaz.Frm_InventarioA2 ventana = new Paq_Interfaz.Frm_InventarioA2();
            ventana.setVisible(true);
            ventana.txtR.setText(usuario);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new Paq_Interfaz.Frm_Usuario().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Paq_Interfaz.Frm_VentasA ventana = new Paq_Interfaz.Frm_VentasA();
        ventana.setVisible(true);
        ventana.lblResponsable.setText(usuario);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Paq_Interfaz.Frm_VentasC ventana = new Paq_Interfaz.Frm_VentasC();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser explorador = new JFileChooser("\\home\\");
        explorador.setDialogTitle("Abrir ubicacion de los reportes...");
        explorador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = explorador.showDialog(null, "Abrir!");
        //Podemos crear un File con lo seleccionado
        File archivo = explorador.getSelectedFile();

        //y guardar una ruta
        String ruta = archivo.getPath();
        //analizamos la respuesta
        switch (seleccion) {
            case JFileChooser.APPROVE_OPTION:
                JOptionPane.showMessageDialog(null, ruta);
                try {
                    String sql = "update valores set direccion=?";
                    PreparedStatement ps = operaciones.Actualizar(sql);
                    ps.setString(1, ruta);
                    int n = ps.executeUpdate();
                    if (n > 0) {
                        JOptionPane.showMessageDialog(null, "RUTA DE REPORTES ACTUALIZADA CORRECTAMENTE");
                    }
                    operaciones.conn.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR LOS DATOS VERIFIQUE QUE SEAN CORRECTOS\n" + e.getMessage());
                }
                break;

            case JFileChooser.CANCEL_OPTION:
                //dio click en cancelar o cerro la ventana
                break;

            case JFileChooser.ERROR_OPTION:
                //llega aqui si sucede un error
                break;
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
//Ejemplo 1 reporte con paso de conexion a bd
        try {
            //asigno la conexion 
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            //asigno ruta del reporte. la cual esta guardada en la bd
            String dir = ruta.getRuta() + "\\Reporte_Ventas.jrxml";
            //creo objeto map y paso parametros de nombre de usuario y la ruta
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            //creo variable del reporte compilado en la direccion dir
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            //paso parametros para construccion del reporte, parametros: reporte, los parametros que usa y la conexion
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            //declaro el visor que mostrara el reporte
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            //muestro el visor
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\Reporte_Clientes.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            /**
             * ***************************************************************
             */
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\proveedores.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        int seleccion = JOptionPane.showOptionDialog(
                null,
                "¿Como desea realizar la consulta de ventas?",
                "Selector de opciones",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Dia", "Mes", "Año"}, // null para YES, NO y CANCEL
                "Dia");
        switch (seleccion) {
            case 0:
                this.jFrame1.setLocationRelativeTo(null);
                this.jFrame1.setVisible(true);
                break;
            case 1:
                this.jFrame2.setLocationRelativeTo(null);
                this.jFrame2.setVisible(true);
                break;
            case 2:
                this.jFrame3.setLocationRelativeTo(null);
                this.jFrame3.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\Reporte_Usuarios.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat Formato = new SimpleDateFormat("dd/MM/yyyy");
        jDateChooser1.getJCalendar().setMaxSelectableDate(new Date());
        fecha = jDateChooser1.getDate();
        if (fecha == null) {
            JOptionPane.showMessageDialog(null, "Fecha Vacia o Invalida Verifique", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            fecha = Formato.format(jDateChooser1.getDate());
            try {
                conn = Paq_Base_Datos.Conexion_DB.geConnection();
                String dir = ruta.getRuta() + "\\Reporte_Ventas_Consulta.jrxml";
                Map<String, Object> p2 = new HashMap<>();
                p2.put("Fecha", fecha);
                p2.put("usuario", usuario);
                p2.put("ruta", ruta.getRuta());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                jFrame1.dispose();
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jFrame1.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jFrame1WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowLostFocus

    }//GEN-LAST:event_jFrame1WindowLostFocus

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jFrame2.dispose();
        String mes = "", mes1 = "";
        if (jMonthChooser2.getMonth() <= 9) {
            mes = "0" + String.valueOf(jMonthChooser2.getMonth() + 1);

        } else {
            mes = String.valueOf(jMonthChooser2.getMonth() + 1);
        }
        switch (jMonthChooser2.getMonth()) {
            case 0:
                mes1 = "enero";
                break;
            case 1:
                mes1 = "febrero";
                break;
            case 2:
                mes1 = "marzo";
                break;
            case 3:
                mes1 = "abril";
                break;
            case 4:
                mes1 = "mayo";
                break;
            case 5:
                mes1 = "junio";
                break;
            case 6:
                mes1 = "julio";
                break;
            case 7:
                mes1 = "agosto";
                break;
            case 8:
                mes1 = "septiembre";
                break;
            case 9:
                mes1 = "octubre";
                break;
            case 10:
                mes1 = "noviembre";
                break;
            case 11:
                mes1 = "diciembre";
                break;
        }
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\Reporte_Ventas_ConsultaM.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("Fecha", mes);
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            p2.put("mes", mes1);
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
            jFrame2.dispose();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.jFrame2.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jFrame2WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame2WindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame2WindowLostFocus

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        /*verifcacion del joptionpanel*/
        String fecha;
        boolean entrada = true;
        if (entrada) {
            fecha = String.valueOf(jYearChooser1.getYear());
            entrada = fecha.matches("\\d{4}");
        }
        /*verifcacion del joptionpanel*/
        if (entrada) {
            this.jFrame3.dispose();
            try {
                conn = Paq_Base_Datos.Conexion_DB.geConnection();
                String dir = ruta.getRuta() + "\\Reporte_Ventas_ConsultaA.jrxml";
                Map<String, Object> p2 = new HashMap<>();
                p2.put("fecha", jYearChooser1.getYear());
                p2.put("usuario", usuario);
                p2.put("ruta", ruta.getRuta());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                jFrame3.dispose();
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Año Vacio o Invalido Verifique", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.jFrame3.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jFrame3WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame3WindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame3WindowLostFocus

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        this.jFrame4.setLocationRelativeTo(null);
        this.jFrame4.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new Paq_Interfaz.Frm_AjusteInventario().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void txtCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMouseClicked

    }//GEN-LAST:event_txtCMouseClicked

    private void cbxNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNActionPerformed
        //variable para determinar si consiguio algo en clientes
        boolean resultado = false;
        try {
            String sql = "select * from clientes where primer_nombre ='" + this.Desencadenar(cbxN.getSelectedItem().toString()) + "'";
            ResultSet rs = operaciones.Consultar(sql);
            while (rs.next()) {
                txtC.setText(rs.getString("cedula"));
                resultado = true;
            }
            operaciones.conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        if (resultado == false) {
            try {
                String sql = "select * from clientes where nombre_empresa ='" + cbxN.getSelectedItem() + "'";
                ResultSet rs = operaciones.Consultar(sql);
                while (rs.next()) {
                    txtC.setText(rs.getString("cedula"));
                    resultado = true;
                }
                operaciones.conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_cbxNActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String codigo, nombre;
        boolean encontro = false;
        try {
            String sql = "select * from clientes where cedula = '" + txtC.getText() + "'";
            ResultSet rs = operaciones.Consultar(sql);
            while (rs.next()) {
                codigo = rs.getString("cod_cliente");
                if (rs.getString("tipo_persona").equals("natural")) {
                    nombre = rs.getString("primer_nombre") + " " + rs.getString("primer_apellido");
                } else {
                    nombre = rs.getString("nombre_empresa");
                }
                encontro = true;
                try {
                    conn = Paq_Base_Datos.Conexion_DB.geConnection();
                    String dir = ruta.getRuta() + "\\Reporte_Venta_Cliente.jrxml";
                    Map<String, Object> p2 = new HashMap<>();
                    p2.put("usuario", usuario);
                    p2.put("ruta", ruta.getRuta());
                    p2.put("nombre", nombre);
                    p2.put("codigo", codigo);
                    JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                    JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
                    JasperViewer visor = new JasperViewer(mostrarReporte, false);
                    visor.setVisible(true);
                    this.jFrame4.dispose();
                } catch (JRException ex) {
                    JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (encontro == false) {
                JOptionPane.showMessageDialog(null, "Cliente no existe", null, JOptionPane.WARNING_MESSAGE);
            }
            operaciones.conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.jFrame4.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed

        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\inventario.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\proveedoresAc.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\proveedoresIn.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\Reporte_ClientesNa.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            /**
             * ***************************************************************
             */
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\Reporte_ClientesJu.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            /**
             * ***************************************************************
             */
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SimpleDateFormat Formato = new SimpleDateFormat("dd/MM/yyyy");
        jDateChooser2.getJCalendar().setMaxSelectableDate(new Date());
        fecha = jDateChooser2.getDate();
        if (fecha == null) {
            JOptionPane.showMessageDialog(null, "Fecha Vacia o Invalida Verifique", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            fecha = Formato.format(jDateChooser2.getDate());
            try {
                conn = Paq_Base_Datos.Conexion_DB.geConnection();
                String dir = ruta.getRuta() + "\\inventarioFe.jrxml";
                Map<String, Object> p2 = new HashMap<>();
                p2.put("Fecha", fecha);
                p2.put("ruta", ruta.getRuta());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                jFrame5.dispose();
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
jFrame5.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jFrame5WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame5WindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame5WindowLostFocus

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
 this.jFrame5.setLocationRelativeTo(null);
        this.jFrame5.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
fecha = cbxL.getSelectedItem().toString().toLowerCase();
            try {
                conn = Paq_Base_Datos.Conexion_DB.geConnection();
                String dir = ruta.getRuta() + "\\inventarioLi.jrxml";
                Map<String, Object> p2 = new HashMap<>();
                p2.put("Fecha", fecha);
                p2.put("ruta", ruta.getRuta());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                jFrame6.dispose();
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
jFrame6.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jFrame6WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame6WindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame6WindowLostFocus

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
   this.jFrame6.setLocationRelativeTo(null);
        this.jFrame6.setVisible(true);  
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
   try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\inventarioDm.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\inventarioSm.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
try {
            conn = Paq_Base_Datos.Conexion_DB.geConnection();
            String dir = ruta.getRuta() + "\\inventarioIs.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("usuario", usuario);
            p2.put("ruta", ruta.getRuta());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conn);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    public void run() {
        //metodo run para que hilo inicie llamando la funcion calcula tiempo y establece el tiempo en el label
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            try {
                calculaTiempo();
                usuario = lblUsuario.getText();

            } catch (ParseException ex) {
                Logger.getLogger(Frm_Menu.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            jLabel4.setText(hora + ":" + minutos + ":" + segundos);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    private void calculaTiempo() throws ParseException {
        //esta funcion genera los valores para el tiempo
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();

        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY);
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxL;
    private javax.swing.JComboBox<String> cbxN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private com.toedter.calendar.JMonthChooser jMonthChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables

    public String Desencadenar(String datos) {
        //funcion para separar cedula de la letra
        String nombre = "";
        int i = 0, j = 0;
        for (i = 0; i < datos.length(); i++) {
            if (datos.charAt(i) == ' ') {

                break;
            } else {
                nombre += datos.charAt(i) + "";
            }
        }
        return nombre;
    }
}
