/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paq_Interfaz;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Navarro
 */
public class Frm_AjusteInventario extends javax.swing.JFrame {

    private ImageIcon icon2 = new javax.swing.ImageIcon(getClass().getResource("/imagenes/tornavica.png"));
    Paq_Base_Datos.Operaciones_BD operaciones = new Paq_Base_Datos.Operaciones_BD();
    Paq_Clases.Cla_Fecha fecha = new Paq_Clases.Cla_Fecha();

    /**
     * Creates new form Frm_login
     */
    public Frm_AjusteInventario() {
        this.look();
        initComponents();
        this.setLocationRelativeTo(null);
        this.Ajustar(lblLogo, icon2);
        this.restringir();
    }
    
    public void restringir(){
        RestrictedTextField restricted3 = new RestrictedTextField(this.txtMaximo);
        restricted3.setOnlyNums(true);
        restricted3.setLimit(6);
        RestrictedTextField restricted4 = new RestrictedTextField(this.txtMinimo);
        restricted4.setOnlyNums(true);
        restricted4.setLimit(6);
        RestrictedTextField rs5 = new RestrictedTextField(this.txtSeguridad);
        rs5.setOnlyNums(true);
        rs5.setLimit(6);
    }

    public void look() {
        //este metodo establece el look and feels de la aplicacion
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
//    public void Llenar(){
//        try {
//            String sql = "select * from valores";
//            ResultSet rs = operaciones.Consultar(sql);
//            while (rs.next()) {
//                txtMinimo.setText(rs.getString("minimo"));
//                txtMaximo.setText(rs.getString("maximo"));
//                txtSeguridad.setText(rs.getString("seguridad"));
//            }
//            operaciones.conn.close();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR LOS DATOS VERIFIQUE QUE SEAN CORRECTOS\n" + e.getMessage());
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMaximo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnE = new javax.swing.JButton();
        txtMinimo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSeguridad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaximo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtMaximo.setToolTipText("Maximo de productos Disponibles en Inventario");
        txtMaximo.setName("TxtUsuario"); // NOI18N
        txtMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras-10.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras-14.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 112, 32));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion de Inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("De Seguridad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, 30));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tornavica.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 70));

        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar-10.png"))); // NOI18N
        btnE.setContentAreaFilled(false);
        btnE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar-14.png"))); // NOI18N
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        jPanel1.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 112, 32));

        txtMinimo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtMinimo.setToolTipText("Minimo de productos Disponibles en Inventario");
        txtMinimo.setName("TxtUsuario"); // NOI18N
        txtMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 70, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Valor Minimo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Valor Maximo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        txtSeguridad.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtSeguridad.setToolTipText("Maximo de productos Disponibles en Inventario");
        txtSeguridad.setName("TxtUsuario"); // NOI18N
        txtSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(txtSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximoActionPerformed

    }//GEN-LAST:event_txtMaximoActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        if (!txtMinimo.getText().equals("") || !txtMaximo.getText().equals("") || !txtSeguridad.getText().equals("")) {
            if (Integer.parseInt(txtMinimo.getText()) > 0) {
                if (Integer.parseInt(txtSeguridad.getText()) > 0) {
                    if (Integer.parseInt(txtSeguridad.getText()) <= Integer.parseInt(txtMinimo.getText())) {
                        if (Integer.parseInt(txtMaximo.getText()) <= 999999 && Integer.parseInt(txtMaximo.getText()) > 0) {
                            if (Integer.parseInt(txtMinimo.getText()) < Integer.parseInt(txtMaximo.getText())) {
                                try {
                                    String sql = "update valores set minimo=?, maximo=?, seguridad=?";
                                    PreparedStatement ps = operaciones.Actualizar(sql);
                                    ps.setInt(1, Integer.parseInt(txtMinimo.getText()));
                                    ps.setInt(2, Integer.parseInt(txtMaximo.getText()));
                                    ps.setInt(3, Integer.parseInt(txtSeguridad.getText()));
                                    int n = ps.executeUpdate();
                                    if (n > 0) {
                                        JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
                                        txtMinimo.setText("");
                                        txtMaximo.setText("");
                                        txtSeguridad.setText("");
                                    }
                                    operaciones.conn.close();
                                    this.dispose();
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR LOS DATOS VERIFIQUE QUE SEAN CORRECTOS\n" + e.getMessage());
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "El valor del minimo debe ser menor al valor del maximo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Los valores deben estar en el rango de  0 y 999.999");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El valor seguridad debe ser menor o igual al valor del minimo");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El valor debe ser mayor a 0");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El valor debe ser mayor a 0");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El valor de Seguridad debe ser mayo a 0");
        }
        
    }//GEN-LAST:event_btnEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            this.dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.requestFocus();
    }//GEN-LAST:event_formWindowLostFocus

    private void txtMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimoActionPerformed

    private void txtSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeguridadActionPerformed

    public void Ajustar(JLabel label, ImageIcon icon) {
        //esta funcion ajusta un icono(parametro) al tamaño del label (parametro)
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icono);
        this.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_AjusteInventario().setVisible(true);
            }
        });
    }

    private void UltimoAcceso() {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtMaximo;
    private javax.swing.JTextField txtMinimo;
    private javax.swing.JTextField txtSeguridad;
    // End of variables declaration//GEN-END:variables
}
